apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{name}}-external-secrets'
  namespace: external-secrets
  labels:
    app: external-secrets
spec:
  goTemplate: true
  generators:
  - cluster: {} # Automatically use all clusters defined within Argo CD
  project: devwithkrishna
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: HEAD
    path: deploy/charts/external-secrets # chart path of external secrets
  destination:
    server: '{{server}}'
    namespace: external-secrets
  syncPolicy:
    syncOptions:
    - createNamespace=true
