apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devwithkrishna
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*' ## it means we are allowed to use any kinds of clusterscoped resources
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
