apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-github-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-store

  target:
    name: argocd-github-secret
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: GITHUB-TOKEN-FOR-ARGOCD
    remoteRef:
      key: GITHUB-TOKEN-FOR-ARGOCD

  # explicit type and name of secret in the Azure KV
  - secretKey: GITHUB-USERNAME
    remoteRef:
      key: secret/GITHUB-USERNAME
