apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
spec:
  goTemplate: true
  generators:
  - cluster: {} # Automatically use all clusters defined within Argo CD
  project: default
  source:
    repoURL: https://github.com/kubernetes/ingress-nginx
    targetRevision: HEAD
    path: charts/ingress-nginx
  destination:
    server: '{{server}}'
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - createNamespace=true
    - PruneLast=true
    - PrunePropagationPolicy=foreground
