apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app: ingress-nginx-controller
spec:
  goTemplate: true
  generators:
  - cluster: {} # Automatically use all clusters defined within Argo CD
  # project: default
  template:
    metadata:
      name: ingress-nginx-{{.cluster}}
    spec:
      project: default
      repoURL: "https://kubernetes.github.io/ingress-nginx"
      chart: "ingress-nginx"
      targetRevision: "4.10.3" # Replace with the desired version
      helm:
        values: |
          controller:
            replicaCount: 2
            service:
              type: LoadBalancer
      destination:
        server: '{{.url}}'
        namespace: ingress-nginx
      syncPolicy:
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - createNamespace=true
        - PruneLast=true
        - PrunePropagationPolicy=foreground
        automated:
          prune: true
          selfHeal: true
